version: "3.8"  

services:
   app:
       build: .
       ports:
          - "5000:5000"
       depends_on:
          - db
       volumes:
          - .:/app
       command: python app.py
       environment:
          DATABASE_URL: "postgresql://postgres:ali@db:5432/avito_mod"
   db:
      image: postgres:13
      environment:
           POSTGRES_USER: postgres        
           POSTGRES_PASSWORD: ali 
           POSTGRES_DB: avito_mod
      volumes:
          - db_data:/var/lib/postgresql/data
      ports:
         - "5432:5432"
      
        
volumes:
   db_data:
      
